sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root


  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLBWNHGoPTWPPWeeXir
    access-key-secret: n4DNeASQRInKE7QQDYAgJcea6iThPK
    bucket-name: foodie-sky
